### PR TITLE
Split collision geometry into three separate meshes for link5

### PR DESCRIPTION
**Pull request by jakewelde**
Hi folks,

This PR adapts the collision geometry meshes for link 5 of the robot, the "least convex" link which is designed with a sort of macaroni shape to allow the outboard links greater range of motion. All the collision meshes seem to have been created as the convex hull of the visual mesh, which is a decent approximation for all the other links but causes some physically perplexing behavior for this particular link when the gripper collides with midair in simulation.

To address this, I split the visual mesh into three components and computed the convex hull of each. This results in a much tighter bound without too much additional overhead.

The collision geometry before: 

collision_before

The collision geometry after:

collision_after

An example of a configuration now possible that was blocked before by self-collision:

tucked

Please let me know your thoughts on this contribution, thank you!

### CODE REVIEW

**Comment by justagist** [comment]
Hi @jakewelde, this looks great, thanks for the PR.
Your collision meshes are definitely more realistic. However, I am not sure if the additional complexity in the model is actually worth having in the simulator. Some of the earlier versions of this repository had very tight collision meshes which were removed and replaced with simple geometric meshes for efficiency. That configuration of the robot you have shown in the end looks like a very unlikely position for the robot in a simulated robot task, but I could be wrong.
I understand the additional overhead is low and that your collision model looks much more realistic, but I can't see how it would add any benefit in a practical scenario. I am happy to be convinced otherwise. Do let me know your thoughts.

**Comment by jakewelde** [comment]
Hi @justagist. Thank you! Your analysis is fair! 

We are using this robot description in the context of a robotics course, and thought it could be confusing to students when collisions occur that are very unrealistic, and only noticed that with this link in particular. But I agree this is not a major practical concern!

We can just use this change on our own fork if we stick to thinking it's necessary. Alternatively, given some free time, I could create an xacro option for switching from coarse to tight collision meshes (say, the union of no more than 3 convex hulls per link) if you think others would benefit from this.

**Comment by justagist** [comment]
Hi @jakewelde, pleased to hear this package is being used for a course!
If you do create a flag for enabling and disabling the tighter mesh, please do let me know and I would definitely merge the PR! Meanwhile, if anyone brings up this problem with the collision, I will direct them to your fork.

**Comment by jakewelde** [comment]
Sounds good, and yes, it's been a great resource for us! Will close for now and reopen at such a time.

**Pull request closed without merging**
